### ISSUE TITLE
Firmalar icin ayri dosyalar mı acilsa?

### ISSUE THREAD

**Issue by aligoren** [tr-spam-calls/tr-spam-calls#4]
Salliyorum finansbank beni hakkari subesinden bile ariyor. Cunku butun telefonlarini engelledim.

Sadece finansbank'a ait bir dosya olsa? Yakinda ana markdown asiri uzayacak gibi.

**vodafone.md**

- bla
- bla2
- bla3

**turkcell.md**

- tbla
- tbla2

**dolandırıcılar.md**

- dbla
- dla2
- dla3
- dla4

gibi olabilir yani.

**Comment by omerayyildiz** [comment]
Bunu @Adem68 de önerdi. Evet öyle bir şey yapmayı planlıyoruz. Ama şimdilik daha fazla veri toplanmasını bekliyoruz.

**Comment by aligoren** [comment]
Okeydir o zaman kapatayim bunu ben. Tesekkurler simdiden ^_^

**Comment by omerayyildiz** [comment]
Rica ederiz ✌🏻
